services:
  redis:
    image: redis:7.2.3-alpine
    ports:
      - 6379:6379
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: "countries_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
